version: '2'

networks:
  avnet:

services:
  mongo:
    image: mongo:3.4
    volumes:
      - ./.db:/data/db
    networks:
      - avnet
    ports:
      - "127.0.0.1:27017:27017"
    container_name: mongo

  elasticsearch:
    image: elasticsearch:5.2-alpine
    volumes:
      - ./.elasticsearch:/usr/share/elasticsearch/data
    networks:
      - avnet
    ports:
      - "127.0.0.1:9200:9200"
    container_name: elasticsearch
